all:
	@echo "Sample Application"
	@echo "Please install the sample application via flevorium, or use a standard make option. To package this application, please see PACKAGING in the main directory."
compile:
	gcc main.c -o sample
install:
	cp sample /usr/local/lab/
remove:
	rm /usr/local/lab/sample
update: remove install

clean:
	rm *.o sample
